name: "[Error] in article"
description: File a
title: "[Bug]: "
labels: ["error in article"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: input
    id: url
    attributes:
      label: Link to the error. You should not need to edit this.
      description: 
      placeholder: https://dbwebb.se
      value: "https://dbwebb.se"
    validations:
      required: true
  - type: textarea
    id: what-error
    attributes:
      label: Describe what the error is?
      description: If it is an error with example code or instructions, also tell us what you error you got when executing?
      placeholder: Something is wrong...
      value: "A text error!"
    validations:
      required: true
  - type: textarea
    id: copied-text
    attributes:
      render: bash
      label: The marked text
      description: This is the text you marked in the article. You should not need to edit this.
      placeholder: Text
      value: "A text error!"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        If it is an error with example code or instructions, also fill in the questions below.
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: Describe what you expect to happen when executing the code/instruction
      placeholder: 4 + 4 should equal 8 not 9.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Execution environment
      description: |
        Where was the code/instruction executed?
         - OS: [e.g. iOS]
         - Language [e.g. Bash command, Python, JS, C#]
         - Program [e.g. terminal, browser, Thonny]
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
